name: Compile LaTeX and Update Metadata

on:
  push:
    # This workflow will run on every push

permissions:
  contents: write

jobs:
  compile_and_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install LaTeX
      run: sudo apt-get install texlive-latex-extra

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          */*.tex

    - name: Compile changed LaTeX documents and update metadata
      run: |
        # echo "All changed files:"
        # echo "${{ steps.changed-files.outputs.all_changed_files }}"
        # echo "---"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # echo "File: $file"
          # echo "Directory: $(dirname "$file")"
          # echo "Number of .tex files in directory: $(ls "$(dirname "$file")"/*.tex | wc -l)"
          # echo "Condition evaluation:"
          # echo "1. Is it a .tex file? [[ $file == */*.tex ]] = $([[ $file == */*.tex ]] && echo "true" || echo "false")"
          # echo "2. Is it the only .tex file? [[ $(ls "$(dirname "$file")"/*.tex | wc -l) -eq 1 ]] = $([[ $(ls "$(dirname "$file")"/*.tex | wc -l) -eq 1 ]] && echo "true" || echo "false")"
          # echo "---"
          if [[ $file == */*.tex && $(ls "$(dirname "$file")"/*.tex | wc -l) -eq 1 ]]; then
            dir=$(dirname "$file")
            filename=$(basename "$file")
            echo "Processing $file"
            
            # Compile LaTeX
            pdflatex -output-directory="$dir" "$file"
            
            # Update metadata
            echo >> "$dir/metadata.txt" 
            echo "Last compiled: $(date)" >> "$dir/metadata.txt"
            echo "Revision by: ${{ github.event.head_commit.author.name }}" >> "$dir/metadata.txt"
            echo "Commit: ${{ github.sha }}" >> "$dir/metadata.txt"
            
            # Add changes to git
            git add "$dir/${filename%.tex}.pdf" "$dir/metadata.txt"
          fi
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Compile LaTeX and update metadata" || echo "No note changes to commit"
        git push